# theme: neon-rose
set -g status on
set -g status-position bottom
set -g status-style "bg=#14000a,fg=#ff007f"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ff66cc,fg=#14000a,bold] #S #[bg=#14000a,fg=#ff66cc,nobold] "
set -g status-right "#[fg=#ff007f]%Y-%m-%d %H:%M #[bg=#ff66cc,fg=#14000a,bold] #h "
setw -g window-status-current-style "bg=#ff66cc,fg=#14000a,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#ff007f"
set -g pane-active-border-style "fg=#ff66cc"
set -g message-style "bg=#ff66cc,fg=#14000a"
