# theme: tomorrow-night-bright
set -g status on
set -g status-position bottom
set -g status-style "bg=#000000,fg=#eaeaea"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#7aa6da,fg=#000000,bold] #S #[bg=#000000,fg=#7aa6da,nobold] "
set -g status-right "#[fg=#eaeaea]%Y-%m-%d %H:%M #[bg=#7aa6da,fg=#000000,bold] #h "
setw -g window-status-current-style "bg=#7aa6da,fg=#000000,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#eaeaea"
set -g pane-active-border-style "fg=#7aa6da"
set -g message-style "bg=#7aa6da,fg=#000000"
