# kitty theme: 94-twilight — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #e0e0e0
background #141414
cursor     #ce6700
selection_background #414868
selection_foreground #e0e0e0
url_color  #7dcfff

color0  #141414
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ce6700
color5  #9b859d
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ce6700
color13 #9b859d
color14 #7dcfff
color15 #e0e0e0
