# kitty theme: 48-crampack-standard — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #cdd6f4
background #1e1e2e
cursor     #89b4fa
selection_background #414868
selection_foreground #cdd6f4
url_color  #7dcfff

color0  #1e1e2e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #89b4fa
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #89b4fa
color13 #bb9af7
color14 #7dcfff
color15 #cdd6f4
