# theme: github-light
set -g status on
set -g status-position bottom
set -g status-style "bg=#ffffff,fg=#24292f"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#0969da,fg=#ffffff,bold] #S #[bg=#ffffff,fg=#0969da,nobold] "
set -g status-right "#[fg=#24292f]%Y-%m-%d %H:%M #[bg=#0969da,fg=#ffffff,bold] #h "
setw -g window-status-current-style "bg=#0969da,fg=#ffffff,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#24292f"
set -g pane-active-border-style "fg=#0969da"
set -g message-style "bg=#0969da,fg=#ffffff"
