# kitty theme: 04-dracula-theme — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #f8f8f2
background #282a36
cursor     #bd93f9
selection_background #414868
selection_foreground #f8f8f2
url_color  #7dcfff

color0  #282a36
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #bd93f9
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #bd93f9
color13 #bb9af7
color14 #7dcfff
color15 #f8f8f2
