# theme: hopscotch
set -g status on
set -g status-position bottom
set -g status-style "bg=#322931,fg=#b9b5b8"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#fd8b19,fg=#322931,bold] #S #[bg=#322931,fg=#fd8b19,nobold] "
set -g status-right "#[fg=#b9b5b8]%Y-%m-%d %H:%M #[bg=#fd8b19,fg=#322931,bold] #h "
setw -g window-status-current-style "bg=#fd8b19,fg=#322931,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#b9b5b8"
set -g pane-active-border-style "fg=#fd8b19"
set -g message-style "bg=#fd8b19,fg=#322931"
