# kitty theme: 28-nord-powerline — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #eceff4
background #2e3440
cursor     #88c0d0
selection_background #414868
selection_foreground #eceff4
url_color  #7dcfff

color0  #2e3440
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #88c0d0
color5  #81a1c1
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #88c0d0
color13 #81a1c1
color14 #7dcfff
color15 #eceff4
