# theme: nerd-font-symbols
set -g status on
set -g status-position bottom
set -g status-style "bg=default,fg=default"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[reverse,bold] #S #[noreverse] "
set -g status-right "%Y-%m-%d %H:%M  #h "
setw -g window-status-current-style "reverse,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g message-style "reverse"
