# ghostty theme: 67-horizon — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = 1c1e26
foreground = cbced0
cursor-color = e95678
selection-background = 414868

palette = 0=#1c1e26
palette = 1=#f7768e
palette = 2=#9ece6a
palette = 3=#e0af68
palette = 4=#e95678
palette = 5=#fac29a
palette = 6=#7dcfff
palette = 7=#a9b1d6
palette = 8=#414868
palette = 9=#f7768e
palette = 10=#9ece6a
palette = 11=#e0af68
palette = 12=#e95678
palette = 13=#fac29a
palette = 14=#7dcfff
palette = 15=#cbced0
