# kitty theme: 35-myth-colorful-twoline — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #f5e0dc
background #1e1e2e
cursor     #cba6f7
selection_background #414868
selection_foreground #f5e0dc
url_color  #7dcfff

color0  #1e1e2e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #cba6f7
color5  #a6e3a1
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #cba6f7
color13 #a6e3a1
color14 #7dcfff
color15 #f5e0dc
