# theme: neon-lime
set -g status on
set -g status-position bottom
set -g status-style "bg=#0a1400,fg=#ccff00"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#bfff00,fg=#0a1400,bold] #S #[bg=#0a1400,fg=#bfff00,nobold] "
set -g status-right "#[fg=#ccff00]%Y-%m-%d %H:%M #[bg=#bfff00,fg=#0a1400,bold] #h "
setw -g window-status-current-style "bg=#bfff00,fg=#0a1400,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#ccff00"
set -g pane-active-border-style "fg=#bfff00"
set -g message-style "bg=#bfff00,fg=#0a1400"
