# alacritty theme: 79-iceberg-light — include via:  import = ["~/.config/theme-picker/active/alacritty.toml"]
[colors.primary]
background = "#e8e9ec"
foreground = "#33374c"

[colors.cursor]
text   = "#e8e9ec"
cursor = "#2d539e"

[colors.selection]
text       = "#33374c"
background = "#414868"

[colors.normal]
black   = "#e8e9ec"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#2d539e"
magenta = "#7759b4"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#2d539e"
magenta = "#7759b4"
cyan    = "#7dcfff"
white   = "#33374c"
