# kitty theme: 79-iceberg-light — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #33374c
background #e8e9ec
cursor     #2d539e
selection_background #414868
selection_foreground #33374c
url_color  #7dcfff

color0  #e8e9ec
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #2d539e
color5  #7759b4
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #2d539e
color13 #7759b4
color14 #7dcfff
color15 #33374c
