"$schema" = "https://starship.rs/config-schema.json"
add_newline = true
palette = "main"

[palettes.main]
bg = "#282828"
fg = "#ebdbb2"
accent = "#fabd2f"
c1 = "#fabd2f"
c2 = "#fe8019"
c3 = "#fb4934"
c4 = "#b8bb26"
c5 = "#83a598"
c6 = "#d3869b"

format = """
[](fg:c1)[ $username ](fg:bg bg:c1 bold)[](fg:c1 bg:c2)[ $directory ](fg:bg bg:c2)[](fg:c2 bg:c3)[ $git_branch ](fg:bg bg:c3)[](fg:c3 bg:c4)[ $nodejs$python ](fg:bg bg:c4)[](fg:c4 bg:c5)[ $cmd_duration ](fg:bg bg:c5)[](fg:c5)
$character"""


[username]
show_always = true
style_user = "fg:fg bg:accent"
style_root = "fg:red bold"
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[@$hostname]($style)"
style = "fg:fg bg:accent"

[directory]
style = "fg:accent bold"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = " "
style = "fg:accent"
format = "[$symbol$branch]($style) "

[git_status]
style = "fg:red"
format = "([$all_status$ahead_behind]($style)) "

[nodejs]
symbol = "⬢ "
format = "[$symbol($version)]($style) "

[python]
symbol = " "
format = "[$symbol($version)]($style) "

[docker_context]
symbol = " "
format = "[$symbol$context]($style) "

[cmd_duration]
min_time = 500
format = "[took $duration]($style) "
style = "yellow"

[status]
disabled = false
format = "[$status]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
