# kitty theme: 93-bluloco-light — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #383a42
background #f9f9f9
cursor     #0098dd
selection_background #414868
selection_foreground #383a42
url_color  #7dcfff

color0  #f9f9f9
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #0098dd
color5  #23974a
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #0098dd
color13 #23974a
color14 #7dcfff
color15 #383a42
