# ghostty theme: 59-synthwave-84 — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = 241b2f
foreground = f7f7ff
cursor-color = ff7edb
selection-background = 495495

palette = 0=#000000
palette = 1=#fe4450
palette = 2=#72f1b8
palette = 3=#fede5d
palette = 4=#03edf9
palette = 5=#ff7edb
palette = 6=#03edf9
palette = 7=#f7f7ff
palette = 8=#495495
palette = 9=#fe4450
palette = 10=#72f1b8
palette = 11=#fede5d
palette = 12=#03edf9
palette = 13=#ff7edb
palette = 14=#03edf9
palette = 15=#f7f7ff
