# kitty theme: 59-synthwave-84 — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #f7f7ff
background #241b2f
cursor     #ff7edb
selection_background #495495
selection_foreground #f7f7ff
url_color  #03edf9

color0  #000000
color1  #fe4450
color2  #72f1b8
color3  #fede5d
color4  #03edf9
color5  #ff7edb
color6  #03edf9
color7  #f7f7ff
color8  #495495
color9  #fe4450
color10 #72f1b8
color11 #fede5d
color12 #03edf9
color13 #ff7edb
color14 #03edf9
color15 #f7f7ff
