# theme: material-darker
set -g status on
set -g status-position bottom
set -g status-style "bg=#212121,fg=#eeffff"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#82aaff,fg=#212121,bold] #S #[bg=#212121,fg=#82aaff,nobold] "
set -g status-right "#[fg=#eeffff]%Y-%m-%d %H:%M #[bg=#82aaff,fg=#212121,bold] #h "
setw -g window-status-current-style "bg=#82aaff,fg=#212121,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#eeffff"
set -g pane-active-border-style "fg=#82aaff"
set -g message-style "bg=#82aaff,fg=#212121"
