# kitty theme: 111-neon-violet — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #9d00ff
background #0d0014
cursor     #7f00ff
selection_background #414868
selection_foreground #9d00ff
url_color  #7dcfff

color0  #0d0014
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7f00ff
color5  #5d00ff
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7f00ff
color13 #5d00ff
color14 #7dcfff
color15 #9d00ff
