# theme: rose-pine-dawn
set -g status on
set -g status-position bottom
set -g status-style "bg=#faf4ed,fg=#575279"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#d7827e,fg=#faf4ed,bold] #S #[bg=#faf4ed,fg=#d7827e,nobold] "
set -g status-right "#[fg=#575279]%Y-%m-%d %H:%M #[bg=#d7827e,fg=#faf4ed,bold] #h "
setw -g window-status-current-style "bg=#d7827e,fg=#faf4ed,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#575279"
set -g pane-active-border-style "fg=#d7827e"
set -g message-style "bg=#d7827e,fg=#faf4ed"
