# kitty theme: 110-neon-lime — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #ccff00
background #0a1400
cursor     #bfff00
selection_background #414868
selection_foreground #ccff00
url_color  #7dcfff

color0  #0a1400
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #bfff00
color5  #aaff00
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #bfff00
color13 #aaff00
color14 #7dcfff
color15 #ccff00
