# theme: shades-of-purple
set -g status on
set -g status-position bottom
set -g status-style "bg=#2d2b55,fg=#ffffff"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#a599e9,fg=#2d2b55,bold] #S #[bg=#2d2b55,fg=#a599e9,nobold] "
set -g status-right "#[fg=#ffffff]%Y-%m-%d %H:%M #[bg=#a599e9,fg=#2d2b55,bold] #h "
setw -g window-status-current-style "bg=#a599e9,fg=#2d2b55,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#ffffff"
set -g pane-active-border-style "fg=#a599e9"
set -g message-style "bg=#a599e9,fg=#2d2b55"
