# theme: ayu-dark
set -g status on
set -g status-position bottom
set -g status-style "bg=#0a0e14,fg=#b3b1ad"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#e6b450,fg=#0a0e14,bold] #S #[bg=#0a0e14,fg=#e6b450,nobold] "
set -g status-right "#[fg=#b3b1ad]%Y-%m-%d %H:%M #[bg=#e6b450,fg=#0a0e14,bold] #h "
setw -g window-status-current-style "bg=#e6b450,fg=#0a0e14,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#b3b1ad"
set -g pane-active-border-style "fg=#e6b450"
set -g message-style "bg=#e6b450,fg=#0a0e14"
