# kitty theme: 91-jellybeans — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #e8e8d3
background #151515
cursor     #88b8f6
selection_background #414868
selection_foreground #e8e8d3
url_color  #7dcfff

color0  #151515
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #88b8f6
color5  #ffb964
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #88b8f6
color13 #ffb964
color14 #7dcfff
color15 #e8e8d3
