# theme: spacegray
set -g status on
set -g status-position bottom
set -g status-style "bg=#2b303b,fg=#c0c5ce"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#bf616a,fg=#2b303b,bold] #S #[bg=#2b303b,fg=#bf616a,nobold] "
set -g status-right "#[fg=#c0c5ce]%Y-%m-%d %H:%M #[bg=#bf616a,fg=#2b303b,bold] #h "
setw -g window-status-current-style "bg=#bf616a,fg=#2b303b,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#c0c5ce"
set -g pane-active-border-style "fg=#bf616a"
set -g message-style "bg=#bf616a,fg=#2b303b"
