set -g status on
set -g status-position bottom
set -g status-style "bg=#1e1e2e,fg=#f5e0dc"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#cba6f7,fg=#1e1e2e,bold] #S #[bg=#1e1e2e,fg=#cba6f7,nobold] "
set -g status-right "#[fg=#f5e0dc]%Y-%m-%d %H:%M #[bg=#cba6f7,fg=#1e1e2e,bold] #h "
setw -g window-status-current-style "bg=#cba6f7,fg=#1e1e2e,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#f5e0dc"
set -g pane-active-border-style "fg=#cba6f7"
set -g message-style "bg=#cba6f7,fg=#1e1e2e"
