# theme: material-ocean
set -g status on
set -g status-position bottom
set -g status-style "bg=#0f111a,fg=#a6accd"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#80cbc4,fg=#0f111a,bold] #S #[bg=#0f111a,fg=#80cbc4,nobold] "
set -g status-right "#[fg=#a6accd]%Y-%m-%d %H:%M #[bg=#80cbc4,fg=#0f111a,bold] #h "
setw -g window-status-current-style "bg=#80cbc4,fg=#0f111a,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#a6accd"
set -g pane-active-border-style "fg=#80cbc4"
set -g message-style "bg=#80cbc4,fg=#0f111a"
