# ghostty theme: 66-vscode-light-plus — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = ffffff
foreground = 000000
cursor-color = 0451a5
selection-background = 414868

palette = 0=#ffffff
palette = 1=#f7768e
palette = 2=#9ece6a
palette = 3=#e0af68
palette = 4=#0451a5
palette = 5=#af00db
palette = 6=#7dcfff
palette = 7=#a9b1d6
palette = 8=#414868
palette = 9=#f7768e
palette = 10=#9ece6a
palette = 11=#e0af68
palette = 12=#0451a5
palette = 13=#af00db
palette = 14=#7dcfff
palette = 15=#000000
