# kitty theme: 66-vscode-light-plus — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #000000
background #ffffff
cursor     #0451a5
selection_background #414868
selection_foreground #000000
url_color  #7dcfff

color0  #ffffff
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #0451a5
color5  #af00db
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #0451a5
color13 #af00db
color14 #7dcfff
color15 #000000
