# theme: snazzy
set -g status on
set -g status-position bottom
set -g status-style "bg=#1e1f29,fg=#eff0eb"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ff6ac1,fg=#1e1f29,bold] #S #[bg=#1e1f29,fg=#ff6ac1,nobold] "
set -g status-right "#[fg=#eff0eb]%Y-%m-%d %H:%M #[bg=#ff6ac1,fg=#1e1f29,bold] #h "
setw -g window-status-current-style "bg=#ff6ac1,fg=#1e1f29,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#eff0eb"
set -g pane-active-border-style "fg=#ff6ac1"
set -g message-style "bg=#ff6ac1,fg=#1e1f29"
