# theme: iceberg-dark
set -g status on
set -g status-position bottom
set -g status-style "bg=#161821,fg=#c6c8d1"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#84a0c6,fg=#161821,bold] #S #[bg=#161821,fg=#84a0c6,nobold] "
set -g status-right "#[fg=#c6c8d1]%Y-%m-%d %H:%M #[bg=#84a0c6,fg=#161821,bold] #h "
setw -g window-status-current-style "bg=#84a0c6,fg=#161821,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#c6c8d1"
set -g pane-active-border-style "fg=#84a0c6"
set -g message-style "bg=#84a0c6,fg=#161821"
