# kitty theme: 113-neon-coral — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #ff6f61
background #140505
cursor     #ff7f50
selection_background #414868
selection_foreground #ff6f61
url_color  #7dcfff

color0  #140505
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ff7f50
color5  #ff4040
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ff7f50
color13 #ff4040
color14 #7dcfff
color15 #ff6f61
