# ghostty theme: 86-elementary-luna — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = 1d1f21
foreground = c5c8c6
cursor-color = 3b81d8
selection-background = 414868

palette = 0=#1d1f21
palette = 1=#f7768e
palette = 2=#9ece6a
palette = 3=#e0af68
palette = 4=#3b81d8
palette = 5=#68b723
palette = 6=#7dcfff
palette = 7=#a9b1d6
palette = 8=#414868
palette = 9=#f7768e
palette = 10=#9ece6a
palette = 11=#e0af68
palette = 12=#3b81d8
palette = 13=#68b723
palette = 14=#7dcfff
palette = 15=#c5c8c6
