# kitty theme: 86-elementary-luna — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #c5c8c6
background #1d1f21
cursor     #3b81d8
selection_background #414868
selection_foreground #c5c8c6
url_color  #7dcfff

color0  #1d1f21
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #3b81d8
color5  #68b723
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #3b81d8
color13 #68b723
color14 #7dcfff
color15 #c5c8c6
