# ghostty theme: 42-tr3ss-viking — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = 1c1f2b
foreground = cad3f5
cursor-color = 7287fd
selection-background = 414868

palette = 0=#1c1f2b
palette = 1=#f7768e
palette = 2=#9ece6a
palette = 3=#e0af68
palette = 4=#7287fd
palette = 5=#4c5491
palette = 6=#7dcfff
palette = 7=#a9b1d6
palette = 8=#414868
palette = 9=#f7768e
palette = 10=#9ece6a
palette = 11=#e0af68
palette = 12=#7287fd
palette = 13=#4c5491
palette = 14=#7dcfff
palette = 15=#cad3f5
