# kitty theme: 58-shades-of-purple — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #ffffff
background #2d2b55
cursor     #a599e9
selection_background #414868
selection_foreground #ffffff
url_color  #7dcfff

color0  #2d2b55
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #a599e9
color5  #fad000
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #a599e9
color13 #fad000
color14 #7dcfff
color15 #ffffff
