# ghostty theme: 109-neon-pink — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = 140008
foreground = ff1493
cursor-color = ff10f0
selection-background = 414868

palette = 0=#140008
palette = 1=#f7768e
palette = 2=#9ece6a
palette = 3=#e0af68
palette = 4=#ff10f0
palette = 5=#ff6ec7
palette = 6=#7dcfff
palette = 7=#a9b1d6
palette = 8=#414868
palette = 9=#f7768e
palette = 10=#9ece6a
palette = 11=#e0af68
palette = 12=#ff10f0
palette = 13=#ff6ec7
palette = 14=#7dcfff
palette = 15=#ff1493
