# kitty theme: 75-tomorrow-night-blue — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #ffffff
background #002451
cursor     #bbdaff
selection_background #414868
selection_foreground #ffffff
url_color  #7dcfff

color0  #002451
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #bbdaff
color5  #ffeead
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #bbdaff
color13 #ffeead
color14 #7dcfff
color15 #ffffff
