# kitty theme: 80-oceanic-next — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #d8dee9
background #1b2b34
cursor     #6699cc
selection_background #65737e
selection_foreground #d8dee9
url_color  #5fb3b3

color0  #1b2b34
color1  #ec5f67
color2  #99c794
color3  #fac863
color4  #6699cc
color5  #c594c5
color6  #5fb3b3
color7  #d8dee9
color8  #65737e
color9  #ec5f67
color10 #99c794
color11 #fac863
color12 #6699cc
color13 #c594c5
color14 #5fb3b3
color15 #d8dee9
