# kitty theme: 29-nordic-pastel-powerline — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #e5e9f0
background #3b4252
cursor     #a3be8c
selection_background #414868
selection_foreground #e5e9f0
url_color  #7dcfff

color0  #3b4252
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #a3be8c
color5  #b48ead
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #a3be8c
color13 #b48ead
color14 #7dcfff
color15 #e5e9f0
