# kitty theme: 57-night-owl — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #d6deeb
background #011627
cursor     #82aaff
selection_background #414868
selection_foreground #d6deeb
url_color  #7dcfff

color0  #011627
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #82aaff
color5  #addb67
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #82aaff
color13 #addb67
color14 #7dcfff
color15 #d6deeb
