# theme: kanagawa-lotus
set -g status on
set -g status-position bottom
set -g status-style "bg=#f2ecbc,fg=#545464"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#4d699b,fg=#f2ecbc,bold] #S #[bg=#f2ecbc,fg=#4d699b,nobold] "
set -g status-right "#[fg=#545464]%Y-%m-%d %H:%M #[bg=#4d699b,fg=#f2ecbc,bold] #h "
setw -g window-status-current-style "bg=#4d699b,fg=#f2ecbc,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#545464"
set -g pane-active-border-style "fg=#4d699b"
set -g message-style "bg=#4d699b,fg=#f2ecbc"
