# kitty theme: 119-neon-rose — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #ff007f
background #14000a
cursor     #ff66cc
selection_background #414868
selection_foreground #ff007f
url_color  #7dcfff

color0  #14000a
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ff66cc
color5  #ff1493
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ff66cc
color13 #ff1493
color14 #7dcfff
color15 #ff007f
