# theme: rose-pine
set -g status on
set -g status-position bottom
set -g status-style "bg=#191724,fg=#e0def4"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ebbcba,fg=#191724,bold] #S #[bg=#191724,fg=#ebbcba,nobold] "
set -g status-right "#[fg=#e0def4]%Y-%m-%d %H:%M #[bg=#ebbcba,fg=#191724,bold] #h "
setw -g window-status-current-style "bg=#ebbcba,fg=#191724,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#e0def4"
set -g pane-active-border-style "fg=#ebbcba"
set -g message-style "bg=#ebbcba,fg=#191724"
