# theme: tomorrow-night
set -g status on
set -g status-position bottom
set -g status-style "bg=#1d1f21,fg=#c5c8c6"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#b294bb,fg=#1d1f21,bold] #S #[bg=#1d1f21,fg=#b294bb,nobold] "
set -g status-right "#[fg=#c5c8c6]%Y-%m-%d %H:%M #[bg=#b294bb,fg=#1d1f21,bold] #h "
setw -g window-status-current-style "bg=#b294bb,fg=#1d1f21,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#c5c8c6"
set -g pane-active-border-style "fg=#b294bb"
set -g message-style "bg=#b294bb,fg=#1d1f21"
