# kitty theme: 114-neon-gold — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #ffc107
background #141200
cursor     #ffd700
selection_background #414868
selection_foreground #ffc107
url_color  #7dcfff

color0  #141200
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ffd700
color5  #ffbf00
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ffd700
color13 #ffbf00
color14 #7dcfff
color15 #ffc107
