# theme: laserwave
set -g status on
set -g status-position bottom
set -g status-style "bg=#27212e,fg=#ffffff"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ff52bf,fg=#27212e,bold] #S #[bg=#27212e,fg=#ff52bf,nobold] "
set -g status-right "#[fg=#ffffff]%Y-%m-%d %H:%M #[bg=#ff52bf,fg=#27212e,bold] #h "
setw -g window-status-current-style "bg=#ff52bf,fg=#27212e,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#ffffff"
set -g pane-active-border-style "fg=#ff52bf"
set -g message-style "bg=#ff52bf,fg=#27212e"
