# theme: horizon
set -g status on
set -g status-position bottom
set -g status-style "bg=#1c1e26,fg=#cbced0"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#e95678,fg=#1c1e26,bold] #S #[bg=#1c1e26,fg=#e95678,nobold] "
set -g status-right "#[fg=#cbced0]%Y-%m-%d %H:%M #[bg=#e95678,fg=#1c1e26,bold] #h "
setw -g window-status-current-style "bg=#e95678,fg=#1c1e26,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#cbced0"
set -g pane-active-border-style "fg=#e95678"
set -g message-style "bg=#e95678,fg=#1c1e26"
