# theme: tomorrow-night-blue
set -g status on
set -g status-position bottom
set -g status-style "bg=#002451,fg=#ffffff"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#bbdaff,fg=#002451,bold] #S #[bg=#002451,fg=#bbdaff,nobold] "
set -g status-right "#[fg=#ffffff]%Y-%m-%d %H:%M #[bg=#bbdaff,fg=#002451,bold] #h "
setw -g window-status-current-style "bg=#bbdaff,fg=#002451,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#ffffff"
set -g pane-active-border-style "fg=#bbdaff"
set -g message-style "bg=#bbdaff,fg=#002451"
