# theme: cyberpunk-neon
set -g status on
set -g status-position bottom
set -g status-style "bg=#000b1e,fg=#0abdc6"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ea00d9,fg=#000b1e,bold] #S #[bg=#000b1e,fg=#ea00d9,nobold] "
set -g status-right "#[fg=#0abdc6]%Y-%m-%d %H:%M #[bg=#ea00d9,fg=#000b1e,bold] #h "
setw -g window-status-current-style "bg=#ea00d9,fg=#000b1e,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#0abdc6"
set -g pane-active-border-style "fg=#ea00d9"
set -g message-style "bg=#ea00d9,fg=#000b1e"
