# kitty theme: 76-tomorrow-night-bright — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #eaeaea
background #000000
cursor     #7aa6da
selection_background #414868
selection_foreground #eaeaea
url_color  #7dcfff

color0  #000000
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa6da
color5  #b9ca4a
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa6da
color13 #b9ca4a
color14 #7dcfff
color15 #eaeaea
