# alacritty theme: 107-neon-blue — include via:  import = ["~/.config/theme-picker/active/alacritty.toml"]
[colors.primary]
background = "#000014"
foreground = "#1f51ff"

[colors.cursor]
text   = "#000014"
cursor = "#00bfff"

[colors.selection]
text       = "#1f51ff"
background = "#414868"

[colors.normal]
black   = "#000014"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#00bfff"
magenta = "#0080ff"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#00bfff"
magenta = "#0080ff"
cyan    = "#7dcfff"
white   = "#1f51ff"
