# kitty theme: 90-snazzy — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #eff0eb
background #1e1f29
cursor     #ff6ac1
selection_background #555555
selection_foreground #eff0eb
url_color  #8be9fe

color0  #000000
color1  #fc4346
color2  #50fb7c
color3  #f0fb8c
color4  #49baff
color5  #fc4cb4
color6  #8be9fe
color7  #ededec
color8  #555555
color9  #fc4346
color10 #50fb7c
color11 #f0fb8c
color12 #49baff
color13 #fc4cb4
color14 #8be9fe
color15 #ededec
