# kitty theme: 98-deep-sea — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #8892b0
background #0a192f
cursor     #64ffda
selection_background #414868
selection_foreground #8892b0
url_color  #7dcfff

color0  #0a192f
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #64ffda
color5  #ccd6f6
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #64ffda
color13 #ccd6f6
color14 #7dcfff
color15 #8892b0
