# theme: vim-default
set -g status on
set -g status-position bottom
set -g status-style "bg=default,fg=default"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=default,fg=default,bold] #S #[bg=default,fg=default,nobold] "
set -g status-right "#[fg=default]%Y-%m-%d %H:%M #[bg=default,fg=default,bold] #h "
setw -g window-status-current-style "bg=default,fg=default,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=default"
set -g pane-active-border-style "fg=default"
set -g message-style "bg=default,fg=default"
