# theme: neon-red
set -g status on
set -g status-position bottom
set -g status-style "bg=#140000,fg=#ff073a"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ff0000,fg=#140000,bold] #S #[bg=#140000,fg=#ff0000,nobold] "
set -g status-right "#[fg=#ff073a]%Y-%m-%d %H:%M #[bg=#ff0000,fg=#140000,bold] #h "
setw -g window-status-current-style "bg=#ff0000,fg=#140000,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#ff073a"
set -g pane-active-border-style "fg=#ff0000"
set -g message-style "bg=#ff0000,fg=#140000"
