# theme: neon-yellow
set -g status on
set -g status-position bottom
set -g status-style "bg=#141400,fg=#fff700"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ffff00,fg=#141400,bold] #S #[bg=#141400,fg=#ffff00,nobold] "
set -g status-right "#[fg=#fff700]%Y-%m-%d %H:%M #[bg=#ffff00,fg=#141400,bold] #h "
setw -g window-status-current-style "bg=#ffff00,fg=#141400,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#fff700"
set -g pane-active-border-style "fg=#ffff00"
set -g message-style "bg=#ffff00,fg=#141400"
