# theme: material-palenight
set -g status on
set -g status-position bottom
set -g status-style "bg=#292d3e,fg=#a6accd"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#c792ea,fg=#292d3e,bold] #S #[bg=#292d3e,fg=#c792ea,nobold] "
set -g status-right "#[fg=#a6accd]%Y-%m-%d %H:%M #[bg=#c792ea,fg=#292d3e,bold] #h "
setw -g window-status-current-style "bg=#c792ea,fg=#292d3e,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#a6accd"
set -g pane-active-border-style "fg=#c792ea"
set -g message-style "bg=#c792ea,fg=#292d3e"
