# theme: neon-green
set -g status on
set -g status-position bottom
set -g status-style "bg=#001400,fg=#39ff14"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#00ff41,fg=#001400,bold] #S #[bg=#001400,fg=#00ff41,nobold] "
set -g status-right "#[fg=#39ff14]%Y-%m-%d %H:%M #[bg=#00ff41,fg=#001400,bold] #h "
setw -g window-status-current-style "bg=#00ff41,fg=#001400,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#39ff14"
set -g pane-active-border-style "fg=#00ff41"
set -g message-style "bg=#00ff41,fg=#001400"
