# theme: oceanic-next
set -g status on
set -g status-position bottom
set -g status-style "bg=#1b2b34,fg=#d8dee9"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#6699cc,fg=#1b2b34,bold] #S #[bg=#1b2b34,fg=#6699cc,nobold] "
set -g status-right "#[fg=#d8dee9]%Y-%m-%d %H:%M #[bg=#6699cc,fg=#1b2b34,bold] #h "
setw -g window-status-current-style "bg=#6699cc,fg=#1b2b34,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#d8dee9"
set -g pane-active-border-style "fg=#6699cc"
set -g message-style "bg=#6699cc,fg=#1b2b34"
