# kitty theme: 104-neon-yellow — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #fff700
background #141400
cursor     #ffff00
selection_background #414868
selection_foreground #fff700
url_color  #7dcfff

color0  #141400
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ffff00
color5  #ffd300
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ffff00
color13 #ffd300
color14 #7dcfff
color15 #fff700
