# ghostty theme: 69-ayu-mirage — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = 1f2430
foreground = cbccc6
cursor-color = ffcc66
selection-background = 1a1f29

palette = 0=#0f1419
palette = 1=#f28779
palette = 2=#d5ff80
palette = 3=#ffd173
palette = 4=#73d0ff
palette = 5=#dfbfff
palette = 6=#95e6cb
palette = 7=#cbccc6
palette = 8=#1a1f29
palette = 9=#f29e74
palette = 10=#d5ff80
palette = 11=#ffd173
palette = 12=#73d0ff
palette = 13=#dfbfff
palette = 14=#95e6cb
palette = 15=#ffffff
