# kitty theme: 69-ayu-mirage — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #cbccc6
background #1f2430
cursor     #ffcc66
selection_background #1a1f29
selection_foreground #cbccc6
url_color  #95e6cb

color0  #0f1419
color1  #f28779
color2  #d5ff80
color3  #ffd173
color4  #73d0ff
color5  #dfbfff
color6  #95e6cb
color7  #cbccc6
color8  #1a1f29
color9  #f29e74
color10 #d5ff80
color11 #ffd173
color12 #73d0ff
color13 #dfbfff
color14 #95e6cb
color15 #ffffff
