# theme: neon-blue
set -g status on
set -g status-position bottom
set -g status-style "bg=#000014,fg=#1f51ff"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#00bfff,fg=#000014,bold] #S #[bg=#000014,fg=#00bfff,nobold] "
set -g status-right "#[fg=#1f51ff]%Y-%m-%d %H:%M #[bg=#00bfff,fg=#000014,bold] #h "
setw -g window-status-current-style "bg=#00bfff,fg=#000014,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#1f51ff"
set -g pane-active-border-style "fg=#00bfff"
set -g message-style "bg=#00bfff,fg=#000014"
