# theme: ayu-light
set -g status on
set -g status-position bottom
set -g status-style "bg=#fafafa,fg=#5c6773"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ff9940,fg=#fafafa,bold] #S #[bg=#fafafa,fg=#ff9940,nobold] "
set -g status-right "#[fg=#5c6773]%Y-%m-%d %H:%M #[bg=#ff9940,fg=#fafafa,bold] #h "
setw -g window-status-current-style "bg=#ff9940,fg=#fafafa,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#5c6773"
set -g pane-active-border-style "fg=#ff9940"
set -g message-style "bg=#ff9940,fg=#fafafa"
