# theme: pure-prompt (minimal)
set -g status on
set -g status-position bottom
set -g status-left "#S "
set -g status-right "%Y-%m-%d %H:%M #h "
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
