# alacritty theme: 33-myth-colorful-pointed — include via:  import = ["~/.config/theme-picker/active/alacritty.toml"]
[colors.primary]
background = "#1e1e2e"
foreground = "#f5e0dc"

[colors.cursor]
text   = "#1e1e2e"
cursor = "#f38ba8"

[colors.selection]
text       = "#f5e0dc"
background = "#414868"

[colors.normal]
black   = "#1e1e2e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#f38ba8"
magenta = "#a6e3a1"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#f38ba8"
magenta = "#a6e3a1"
cyan    = "#7dcfff"
white   = "#f5e0dc"
