# theme: ayu-mirage
set -g status on
set -g status-position bottom
set -g status-style "bg=#1f2430,fg=#cbccc6"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ffcc66,fg=#1f2430,bold] #S #[bg=#1f2430,fg=#ffcc66,nobold] "
set -g status-right "#[fg=#cbccc6]%Y-%m-%d %H:%M #[bg=#ffcc66,fg=#1f2430,bold] #h "
setw -g window-status-current-style "bg=#ffcc66,fg=#1f2430,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#cbccc6"
set -g pane-active-border-style "fg=#ffcc66"
set -g message-style "bg=#ffcc66,fg=#1f2430"
