# theme: twilight
set -g status on
set -g status-position bottom
set -g status-style "bg=#141414,fg=#e0e0e0"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ce6700,fg=#141414,bold] #S #[bg=#141414,fg=#ce6700,nobold] "
set -g status-right "#[fg=#e0e0e0]%Y-%m-%d %H:%M #[bg=#ce6700,fg=#141414,bold] #h "
setw -g window-status-current-style "bg=#ce6700,fg=#141414,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#e0e0e0"
set -g pane-active-border-style "fg=#ce6700"
set -g message-style "bg=#ce6700,fg=#141414"
