# ghostty theme: 95-seti — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = 151718
foreground = cfd2d1
cursor-color = 55b5db
selection-background = 414868

palette = 0=#151718
palette = 1=#f7768e
palette = 2=#9ece6a
palette = 3=#e0af68
palette = 4=#55b5db
palette = 5=#9fca56
palette = 6=#7dcfff
palette = 7=#a9b1d6
palette = 8=#414868
palette = 9=#f7768e
palette = 10=#9ece6a
palette = 11=#e0af68
palette = 12=#55b5db
palette = 13=#9fca56
palette = 14=#7dcfff
palette = 15=#cfd2d1
