# kitty theme: 95-seti — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #cfd2d1
background #151718
cursor     #55b5db
selection_background #414868
selection_foreground #cfd2d1
url_color  #7dcfff

color0  #151718
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #55b5db
color5  #9fca56
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #55b5db
color13 #9fca56
color14 #7dcfff
color15 #cfd2d1
