# theme: neon-amber
set -g status on
set -g status-position bottom
set -g status-style "bg=#140800,fg=#ff8c00"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ffbf00,fg=#140800,bold] #S #[bg=#140800,fg=#ffbf00,nobold] "
set -g status-right "#[fg=#ff8c00]%Y-%m-%d %H:%M #[bg=#ffbf00,fg=#140800,bold] #h "
setw -g window-status-current-style "bg=#ffbf00,fg=#140800,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#ff8c00"
set -g pane-active-border-style "fg=#ffbf00"
set -g message-style "bg=#ffbf00,fg=#140800"
