# theme: neon-magenta
set -g status on
set -g status-position bottom
set -g status-style "bg=#0a0014,fg=#ff10f0"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ff00ff,fg=#0a0014,bold] #S #[bg=#0a0014,fg=#ff00ff,nobold] "
set -g status-right "#[fg=#ff10f0]%Y-%m-%d %H:%M #[bg=#ff00ff,fg=#0a0014,bold] #h "
setw -g window-status-current-style "bg=#ff00ff,fg=#0a0014,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#ff10f0"
set -g pane-active-border-style "fg=#ff00ff"
set -g message-style "bg=#ff00ff,fg=#0a0014"
