# theme: seti
set -g status on
set -g status-position bottom
set -g status-style "bg=#151718,fg=#cfd2d1"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#55b5db,fg=#151718,bold] #S #[bg=#151718,fg=#55b5db,nobold] "
set -g status-right "#[fg=#cfd2d1]%Y-%m-%d %H:%M #[bg=#55b5db,fg=#151718,bold] #h "
setw -g window-status-current-style "bg=#55b5db,fg=#151718,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#cfd2d1"
set -g pane-active-border-style "fg=#55b5db"
set -g message-style "bg=#55b5db,fg=#151718"
