# kitty theme: 106-neon-red — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #ff073a
background #140000
cursor     #ff0000
selection_background #414868
selection_foreground #ff073a
url_color  #7dcfff

color0  #140000
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ff0000
color5  #ff3131
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ff0000
color13 #ff3131
color14 #7dcfff
color15 #ff073a
