# ghostty theme: 73-kanagawa-lotus — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = f2ecbc
foreground = 545464
cursor-color = 4d699b
selection-background = 414868

palette = 0=#f2ecbc
palette = 1=#f7768e
palette = 2=#9ece6a
palette = 3=#e0af68
palette = 4=#4d699b
palette = 5=#b35b79
palette = 6=#7dcfff
palette = 7=#a9b1d6
palette = 8=#414868
palette = 9=#f7768e
palette = 10=#9ece6a
palette = 11=#e0af68
palette = 12=#4d699b
palette = 13=#b35b79
palette = 14=#7dcfff
palette = 15=#545464
