# kitty theme: 73-kanagawa-lotus — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #545464
background #f2ecbc
cursor     #4d699b
selection_background #414868
selection_foreground #545464
url_color  #7dcfff

color0  #f2ecbc
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #4d699b
color5  #b35b79
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #4d699b
color13 #b35b79
color14 #7dcfff
color15 #545464
