# theme: everforest-starship
set -g status on
set -g status-position bottom
set -g status-style "bg=#2d353b,fg=#d3c6aa"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#a7c080,fg=#2d353b,bold] #S #[bg=#2d353b,fg=#a7c080,nobold] "
set -g status-right "#[fg=#d3c6aa]%Y-%m-%d %H:%M #[bg=#a7c080,fg=#2d353b,bold] #h "
setw -g window-status-current-style "bg=#a7c080,fg=#2d353b,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#d3c6aa"
set -g pane-active-border-style "fg=#a7c080"
set -g message-style "bg=#a7c080,fg=#2d353b"
