# theme: neon-gold
set -g status on
set -g status-position bottom
set -g status-style "bg=#141200,fg=#ffc107"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ffd700,fg=#141200,bold] #S #[bg=#141200,fg=#ffd700,nobold] "
set -g status-right "#[fg=#ffc107]%Y-%m-%d %H:%M #[bg=#ffd700,fg=#141200,bold] #h "
setw -g window-status-current-style "bg=#ffd700,fg=#141200,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#ffc107"
set -g pane-active-border-style "fg=#ffd700"
set -g message-style "bg=#ffd700,fg=#141200"
