# theme: one-dark-pro-starship
set -g status on
set -g status-position bottom
set -g status-style "bg=#282c34,fg=#abb2bf"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#61afef,fg=#282c34,bold] #S #[bg=#282c34,fg=#61afef,nobold] "
set -g status-right "#[fg=#abb2bf]%Y-%m-%d %H:%M #[bg=#61afef,fg=#282c34,bold] #h "
setw -g window-status-current-style "bg=#61afef,fg=#282c34,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#abb2bf"
set -g pane-active-border-style "fg=#61afef"
set -g message-style "bg=#61afef,fg=#282c34"
