# kitty theme: 105-neon-orange — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #ff7f00
background #140a00
cursor     #ff6700
selection_background #414868
selection_foreground #ff7f00
url_color  #7dcfff

color0  #140a00
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ff6700
color5  #ff4500
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ff6700
color13 #ff4500
color14 #7dcfff
color15 #ff7f00
