# theme: base16-eighties
set -g status on
set -g status-position bottom
set -g status-style "bg=#2d2d2d,fg=#d3d0c8"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#6699cc,fg=#2d2d2d,bold] #S #[bg=#2d2d2d,fg=#6699cc,nobold] "
set -g status-right "#[fg=#d3d0c8]%Y-%m-%d %H:%M #[bg=#6699cc,fg=#2d2d2d,bold] #h "
setw -g window-status-current-style "bg=#6699cc,fg=#2d2d2d,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#d3d0c8"
set -g pane-active-border-style "fg=#6699cc"
set -g message-style "bg=#6699cc,fg=#2d2d2d"
