# kitty theme: 100-poimandres — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #a6accd
background #1b1e28
cursor     #5de4c7
selection_background #414868
selection_foreground #a6accd
url_color  #7dcfff

color0  #1b1e28
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #5de4c7
color5  #add7ff
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #5de4c7
color13 #add7ff
color14 #7dcfff
color15 #a6accd
