# theme: neon-violet
set -g status on
set -g status-position bottom
set -g status-style "bg=#0d0014,fg=#9d00ff"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#7f00ff,fg=#0d0014,bold] #S #[bg=#0d0014,fg=#7f00ff,nobold] "
set -g status-right "#[fg=#9d00ff]%Y-%m-%d %H:%M #[bg=#7f00ff,fg=#0d0014,bold] #h "
setw -g window-status-current-style "bg=#7f00ff,fg=#0d0014,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#9d00ff"
set -g pane-active-border-style "fg=#7f00ff"
set -g message-style "bg=#7f00ff,fg=#0d0014"
