# kitty theme: 12-pastel-powerline — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #dcdcdc
background #1e1e1e
cursor     #ffd6a5
selection_background #414868
selection_foreground #dcdcdc
url_color  #7dcfff

color0  #1e1e1e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ffd6a5
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ffd6a5
color13 #bb9af7
color14 #7dcfff
color15 #dcdcdc
