# kitty theme: 89-panda — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #e6e6e6
background #292a2b
cursor     #ff75b5
selection_background #414868
selection_foreground #e6e6e6
url_color  #7dcfff

color0  #292a2b
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ff75b5
color5  #19f9d8
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ff75b5
color13 #19f9d8
color14 #7dcfff
color15 #e6e6e6
