# theme: neon-emerald
set -g status on
set -g status-position bottom
set -g status-style "bg=#001408,fg=#00ff7f"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#50c878,fg=#001408,bold] #S #[bg=#001408,fg=#50c878,nobold] "
set -g status-right "#[fg=#00ff7f]%Y-%m-%d %H:%M #[bg=#50c878,fg=#001408,bold] #h "
setw -g window-status-current-style "bg=#50c878,fg=#001408,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#00ff7f"
set -g pane-active-border-style "fg=#50c878"
set -g message-style "bg=#50c878,fg=#001408"
