# kitty theme: 08-pure-prompt — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #c0caf5
background #1a1b26
cursor     #a3be8c
selection_background #414868
selection_foreground #c0caf5
url_color  #7dcfff

color0  #1a1b26
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #a3be8c
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #a3be8c
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5
