# kitty theme: 88-laserwave — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #ffffff
background #27212e
cursor     #ff52bf
selection_background #414868
selection_foreground #ffffff
url_color  #7dcfff

color0  #27212e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ff52bf
color5  #eb64b9
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ff52bf
color13 #eb64b9
color14 #7dcfff
color15 #ffffff
