# kitty theme: 102-neon-cyan — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #00ffff
background #001414
cursor     #00f5ff
selection_background #414868
selection_foreground #00ffff
url_color  #7dcfff

color0  #001414
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #00f5ff
color5  #0080ff
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #00f5ff
color13 #0080ff
color14 #7dcfff
color15 #00ffff
