# theme: cobalt2
set -g status on
set -g status-position bottom
set -g status-style "bg=#193549,fg=#ffffff"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#ffc600,fg=#193549,bold] #S #[bg=#193549,fg=#ffc600,nobold] "
set -g status-right "#[fg=#ffffff]%Y-%m-%d %H:%M #[bg=#ffc600,fg=#193549,bold] #h "
setw -g window-status-current-style "bg=#ffc600,fg=#193549,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#ffffff"
set -g pane-active-border-style "fg=#ffc600"
set -g message-style "bg=#ffc600,fg=#193549"
