# kitty theme: 36-myth-orange-pointed — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #fab387
background #1e1e2e
cursor     #fab387
selection_background #414868
selection_foreground #fab387
url_color  #7dcfff

color0  #1e1e2e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #fab387
color5  #f9e2af
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #fab387
color13 #f9e2af
color14 #7dcfff
color15 #fab387
