set -g status on
set -g status-position bottom
set -g status-style "bg=#1f1f28,fg=#dcd7ba"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#7e9cd8,fg=#1f1f28,bold] #S #[bg=#1f1f28,fg=#7e9cd8,nobold] "
set -g status-right "#[fg=#dcd7ba]%Y-%m-%d %H:%M #[bg=#7e9cd8,fg=#1f1f28,bold] #h "
setw -g window-status-current-style "bg=#7e9cd8,fg=#1f1f28,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#dcd7ba"
set -g pane-active-border-style "fg=#7e9cd8"
set -g message-style "bg=#7e9cd8,fg=#1f1f28"
