# theme: mariana
set -g status on
set -g status-position bottom
set -g status-style "bg=#343d46,fg=#d8dee9"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#5fb3b3,fg=#343d46,bold] #S #[bg=#343d46,fg=#5fb3b3,nobold] "
set -g status-right "#[fg=#d8dee9]%Y-%m-%d %H:%M #[bg=#5fb3b3,fg=#343d46,bold] #h "
setw -g window-status-current-style "bg=#5fb3b3,fg=#343d46,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#d8dee9"
set -g pane-active-border-style "fg=#5fb3b3"
set -g message-style "bg=#5fb3b3,fg=#343d46"
