# theme: bluloco-light
set -g status on
set -g status-position bottom
set -g status-style "bg=#f9f9f9,fg=#383a42"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#0098dd,fg=#f9f9f9,bold] #S #[bg=#f9f9f9,fg=#0098dd,nobold] "
set -g status-right "#[fg=#383a42]%Y-%m-%d %H:%M #[bg=#0098dd,fg=#f9f9f9,bold] #h "
setw -g window-status-current-style "bg=#0098dd,fg=#f9f9f9,bold"
setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "
set -g pane-border-style "fg=#383a42"
set -g pane-active-border-style "fg=#0098dd"
set -g message-style "bg=#0098dd,fg=#f9f9f9"
