# kitty theme: 60-cyberpunk-neon — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #0abdc6
background #000b1e
cursor     #ea00d9
selection_background #414868
selection_foreground #0abdc6
url_color  #7dcfff

color0  #000b1e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #ea00d9
color5  #fde400
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #ea00d9
color13 #fde400
color14 #7dcfff
color15 #0abdc6
