# ghostty theme: 96-hopscotch — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = 322931
foreground = b9b5b8
cursor-color = fd8b19
selection-background = 414868

palette = 0=#322931
palette = 1=#f7768e
palette = 2=#9ece6a
palette = 3=#e0af68
palette = 4=#fd8b19
palette = 5=#149b93
palette = 6=#7dcfff
palette = 7=#a9b1d6
palette = 8=#414868
palette = 9=#f7768e
palette = 10=#9ece6a
palette = 11=#e0af68
palette = 12=#fd8b19
palette = 13=#149b93
palette = 14=#7dcfff
palette = 15=#b9b5b8
