# kitty theme: 96-hopscotch — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #b9b5b8
background #322931
cursor     #fd8b19
selection_background #414868
selection_foreground #b9b5b8
url_color  #7dcfff

color0  #322931
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #fd8b19
color5  #149b93
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #fd8b19
color13 #149b93
color14 #7dcfff
color15 #b9b5b8
