# kitty theme: 39-fang2hou-gruvbox-rainbow — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #ebdbb2
background #282828
cursor     #fabd2f
selection_background #414868
selection_foreground #ebdbb2
url_color  #7dcfff

color0  #282828
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #fabd2f
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #fabd2f
color13 #bb9af7
color14 #7dcfff
color15 #ebdbb2
