# alacritty theme: 99-mariana — include via:  import = ["~/.config/theme-picker/active/alacritty.toml"]
[colors.primary]
background = "#343d46"
foreground = "#d8dee9"

[colors.cursor]
text   = "#343d46"
cursor = "#5fb3b3"

[colors.selection]
text       = "#d8dee9"
background = "#414868"

[colors.normal]
black   = "#343d46"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#5fb3b3"
magenta = "#fac863"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#5fb3b3"
magenta = "#fac863"
cyan    = "#7dcfff"
white   = "#d8dee9"
