# kitty theme: 99-mariana — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #d8dee9
background #343d46
cursor     #5fb3b3
selection_background #414868
selection_foreground #d8dee9
url_color  #7dcfff

color0  #343d46
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #5fb3b3
color5  #fac863
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #5fb3b3
color13 #fac863
color14 #7dcfff
color15 #d8dee9
