# ghostty theme: 70-ayu-light — include via:  config-file = ~/.config/theme-picker/active/ghostty.conf
background = fafafa
foreground = 5c6773
cursor-color = ff9940
selection-background = 828c99

palette = 0=#000000
palette = 1=#f0533a
palette = 2=#5e9700
palette = 3=#f29718
palette = 4=#41a6d9
palette = 5=#9d57d3
palette = 6=#4dbf99
palette = 7=#5c6773
palette = 8=#828c99
palette = 9=#f0533a
palette = 10=#5e9700
palette = 11=#f29718
palette = 12=#41a6d9
palette = 13=#9d57d3
palette = 14=#4dbf99
palette = 15=#000000
