# kitty theme: 70-ayu-light — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #5c6773
background #fafafa
cursor     #ff9940
selection_background #828c99
selection_foreground #5c6773
url_color  #4dbf99

color0  #000000
color1  #f0533a
color2  #5e9700
color3  #f29718
color4  #41a6d9
color5  #9d57d3
color6  #4dbf99
color7  #5c6773
color8  #828c99
color9  #f0533a
color10 #5e9700
color11 #f29718
color12 #41a6d9
color13 #9d57d3
color14 #4dbf99
color15 #000000
