# kitty theme: 85-pop-os — include via:  include ~/.config/theme-picker/active/kitty.conf
foreground #cccccc
background #1a1a1a
cursor     #48b9c7
selection_background #414868
selection_foreground #cccccc
url_color  #7dcfff

color0  #1a1a1a
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #48b9c7
color5  #faa41a
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #48b9c7
color13 #faa41a
color14 #7dcfff
color15 #cccccc
